-- MySQL Script generated by MySQL Workbench
-- Sat May  5 14:46:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PogodynkaTest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PogodynkaTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pogodaembedded` DEFAULT CHARACTER SET utf8 ;
USE `pogodaembedded` ;

-- -----------------------------------------------------
-- Table `pogodaembedded`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pogodaembedded`.`Data` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Temperature` DOUBLE NOT NULL,
  `Humidity` DOUBLE NOT NULL,
  `DateTime` DATETIME NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
